FROM alpine:3.3
MAINTAINER Guoqiang Chen <subchen@gmail.com>

RUN echo -e "http://mirrors.gigenet.com/alpinelinux/v3.4/main\nhttp://mirrors.gigenet.com/alpinelinux/v3.4/community" > /etc/apk/repositories \
 && apk add --no-cache curl tar

